{{- if .Values.app.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "api.fullname" . }}-settings
data:
  appsettings.json: |-
    {
      "ConnectionStrings": {
        "PgConnection": "server={{ .Values.app.settings.server }}; port={{ .Values.app.settings.port }}; database=weather; user id={{ .Values.app.settings.user_id }}; password={{ .Values.app.settings.password }};"
      },
      "AllowedHosts": "*",
      "Serilog": {
        "Using": [ "Serilog.Sinks.File", "Serilog.Sinks.Console" ],
        "MinimumLevel": {
          "Default": "Information"
        },
        "WriteTo": [
          {
            "Name": "Console"
          }
        ]
      }
    }
{{- end}}
