---
- block:
  - name: Add the user 'prometheus'
    user:
      name: prometheus

  - name: "Download file app {{ app_name }}"
    ansible.builtin.unarchive:
      src: "{{ prometheus_url }}"
      dest: "/usr/local/src"
      owner: prometheus
      group: prometheus
      remote_src: yes

  - name: Create a symbolic link
    file:
      src: "/usr/local/src/prometheus-{{ prometheus_version }}.linux-amd64"
      dest: "{{ base_app_dir }}"
      owner: prometheus
      group: prometheus
      state: link
  when:
    - update == 'Yes'
    - install == 'Yes'

- name: Add prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ base_app_dir }}/prometheus.yml"
    owner: prometheus
    group: prometheus
  notify: "restart_service_{{ app_name }}"

- name: Add prometheus_rules.yml
  template:
    src: prometheus.rules.yml.j2
    dest: "{{ base_app_dir }}/prometheus_rules.yml"
    owner: prometheus
    group: prometheus
  notify: "restart_service_{{ app_name }}"

- name: Create a file systemd unit
  template:
    src: SystemdUnit.j2
    dest: "/etc/systemd/system/{{ app_name }}.service"
  notify: "restart_service_{{ app_name }}"
